package com.semantyca.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-08-30T11:32:38.042+03:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.prh.fi/YrttiInvoicing", name = "YrttiInvoicingPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface YrttiInvoicingPort {

    @WebMethod(operationName = "YrttiInvoicing", action = "http://www.prh.fi/YrttiInvoicing")
    @WebResult(name = "YrttiInvoicingResponse", targetNamespace = "http://www.prh.fi/YrttiInvoicing", partName = "YrttiInvoicingResponse")
    public YrttiInvoicingResponse yrttiInvoicing(

            @WebParam(partName = "YrttiInvoicingRequest", name = "YrttiInvoicingRequest", targetNamespace = "http://www.prh.fi/YrttiInvoicing")
                    YrttiInvoicingRequest yrttiInvoicingRequest
    );
}
