package com.semantyca.webservices;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-08-30T11:32:38.110+03:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "YrttiInvoicingService",
                  wsdlLocation = "file:/C:/Users/kaira.kuliyeva/IdeaProjects/RESTServer11/src/main/resources/wsdl/YrttiContractCustomerInvoicing.wsdl",
                  targetNamespace = "http://www.prh.fi/YrttiInvoicing")
public class YrttiInvoicingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.prh.fi/YrttiInvoicing", "YrttiInvoicingService");
    public final static QName YrttiInvoicing = new QName("http://www.prh.fi/YrttiInvoicing", "YrttiInvoicing");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/kaira.kuliyeva/IdeaProjects/RESTServer11/src/main/resources/wsdl/YrttiContractCustomerInvoicing.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(YrttiInvoicingService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/kaira.kuliyeva/IdeaProjects/RESTServer11/src/main/resources/wsdl/YrttiContractCustomerInvoicing.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public YrttiInvoicingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YrttiInvoicingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YrttiInvoicingService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public YrttiInvoicingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public YrttiInvoicingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public YrttiInvoicingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns YrttiInvoicingPort
     */
    @WebEndpoint(name = "YrttiInvoicing")
    public YrttiInvoicingPort getYrttiInvoicing() {
        return super.getPort(YrttiInvoicing, YrttiInvoicingPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YrttiInvoicingPort
     */
    @WebEndpoint(name = "YrttiInvoicing")
    public YrttiInvoicingPort getYrttiInvoicing(WebServiceFeature... features) {
        return super.getPort(YrttiInvoicing, YrttiInvoicingPort.class, features);
    }

}
